// "use client"
import Image from "next/image";
import JobCard from "../../components/JobCard";
import { type JobCardProps } from "../../types/JobCardProps";
import { promises as fs } from 'fs';
import Dashboard from "../../components/Dashboard";
import { useGetAllOpportunitiesQuery } from "../../service/opportunities";
import { ReduxProvider } from "../../service/ReduxProvider";
import type { Metadata } from "next";
import App from "../../components/App";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return <App />
}
