import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Poppins, Epilogue } from 'next/font/google'

export const poppins = Poppins({
  subsets: ['latin'],
  weight: '900'
})

export const epilogue = Epilogue({
  subsets: ['latin'],
  weight: ['400', '600']
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable} ${geistMono.variable} 
          p-8 antialiased`}
      >
        {children}
      </body>
    </html>
  );
}

